### ISSUE TITLE
Error Unauthorized status 401

### ISSUE THREAD

**Issue by AntoineKouma** [NightfallGT/Twitch-Follow-Bot#1]
Enter name of channel to follow [e.g Ninja]: test1234
[21:16:07] Followed test123 ID: 0000
[21:16:07] Followed test123 ID: 0000
[21:16:08] Error in following user.
[21:16:08] {"error":"Unauthorized","status":401,"message":"The \"Authorization\" token is invalid."}
[21:16:08] Followed test123 ID: 0000
Traceback (most recent call last):
  File "C:\Users\xxx\Desktop\Follow Bot by NightfallGT\Twitch-Follow-Bot\main.py", line 243, in <module>
    main()
  File "C:\Users\xxx\Desktop\Follow Bot by NightfallGT\Twitch-Follow-Bot\main.py", line 240, in main
    logic()
  File "C:\Users\xxx\Desktop\Follow Bot by NightfallGT\Twitch-Follow-Bot\main.py", line 215, in logic
    Follow(channel).follow()
  File "C:\Users\xxx\Desktop\Follow Bot by NightfallGT\Twitch-Follow-Bot\main.py", line 157, in follow
    followed = self._follow(self.channel_id)
  File "C:\Users\xxx\Desktop\Follow Bot by NightfallGT\Twitch-Follow-Bot\main.py", line 94, in _follow
    followed_user = r.json()[0]['data']['followUser']['follow']['user']
TypeError: 'NoneType' object is not subscriptable

C:\Users\xxx\Desktop\Follow Bot by NightfallGT\Twitch-Follow-Bot>
```

**Comment by NightfallGT** [comment]
Added exception handling to the code. Can you try again (with the latest version) and tell me what your error is?

**Comment by AntoineKouma** [comment]
Hey Nightfall, is working now.
